# Generated by Django 5.0.4 on 2024-07-06 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_birthday_item_citizenship_item_civil_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='item',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='item',
            name='civil_status',
        ),
        migrations.RemoveField(
            model_name='item',
            name='college_course_program',
        ),
        migrations.RemoveField(
            model_name='item',
            name='elementary',
        ),
        migrations.RemoveField(
            model_name='item',
            name='emergency_contact_address',
        ),
        migrations.RemoveField(
            model_name='item',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='item',
            name='emergency_contact_relationship',
        ),
        migrations.RemoveField(
            model_name='item',
            name='fathers_first_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='fathers_last_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='fathers_middle_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='fathers_occupation',
        ),
        migrations.RemoveField(
            model_name='item',
            name='mothers_first_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='mothers_last_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='mothers_middle_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='mothers_occupation',
        ),
        migrations.RemoveField(
            model_name='item',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='item',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='item',
            name='secondary',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='item',
            name='vocational_trade_course',
        ),
    ]
